[package]
name = "hvmcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imp_hvm = { path = "../imp_hvm" }
js_imp =  { path = "../js_imp" }
pyhvm =  { path = "../pyhvm" }

clap = "4.0.29"
